name: Deploy to GitHub pages

on:
    workflow_dispatch:
    schedule:
        - cron: "0 9 * * *"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - run: |
                  git init
                  git add -A
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git commit -m 'deploy'
              working-directory: ./public
            - uses: JamesIves/github-pages-deploy-action@v4.3.3
              with:
                  branch: gh-pages
                  folder: public
