name: Group JSON API

on:
    workflow_dispatch:
    schedule:
        - cron: "0 * * * *"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 18
            - name: Generate new data
              run: npm install && npm run group-data
            - name: Read manifestIdGroup.txt
              id: manifestId
              uses: juliangruber/read-file-action@v1
              with:
                  path: ./manifestIdGroup.txt
            - name: Commit & push changes
              run: |
                  git config user.name ByMykel
                  git config user.email bymykel5@gmail.com
                  git add .
                  git diff --quiet && git diff --staged --quiet || git commit -m "[bot::group] manifest ${{ steps.manifestId.outputs.content }}" --author="41898282+github-actions[bot]@users.noreply.github.com>"
                  git push origin main
