name: Update JSON API

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16"
      - run: npm install
      - run: npm run group-data
      - run: |
          git config user.name ByMykel
          git config user.email bymykel5@gmail.com
          git add .

          changed_files=$(git status --porcelain | awk '{print $2}')

          git diff --quiet && git diff --staged --quiet || git commit -m "[bot] Update JSON API | $(echo "$changed_files" | wc -l) files" -m "$(echo "$changed_files")"
          git push origin main
