name: Group JSON API

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16"
      - run: npm install
      - run: npm run group-data
      - run: |
          git config user.name ByMykel
          git config user.email bymykel5@gmail.com
          git add .

          # Get a list of changed files
          changed_files=$(git status --porcelain | awk '{print $2}')

          # Organize the changed files by language/region
          if ! git diff --quiet || ! git diff --staged --quiet; then
              organized_changes=""
              for lang in $(echo "$changed_files" | cut -d'/' -f 3 | sort | uniq); do
                  # List files changed for this language, and remove the "public/api/lang" prefix for clarity
                  files_changed_for_lang=$(echo "$changed_files" | grep "/$lang/" | sed "s|public/api/$lang/||")
                  organized_changes="${organized_changes}\n\n${lang}:\n${files_changed_for_lang}"
              done

              commit_message="[bot] Group JSON API"
              detailed_changes="Affected languages and files:${organized_changes}"

              # Check for changes and then commit
              git commit -m "$commit_message" -m "$(echo -e "$detailed_changes")"
          fi
