name: Update JSON API

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16"
      - run: npm install
      - run: npm run update-data
      - run: |
          git config user.name ByMykel
          git config user.email bymykel5@gmail.com
          git add .
          files_changed=$(git diff --name-only | wc -l)
          if [ "$files_changed" -gt 0 ]; then
            git commit -m "[bot] Update JSON API with latest info ($files_changed files changed)"
            git push origin main
          else
            echo "No changes detected. Skipping commit and push."
          fi

